language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
  - jdk_switcher use oraclejdk7
  - mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash) -t e8098a9a-54dd-4765-a9c2-2addc1a27f7a
