language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
  - mvn test -B
  - jdk_switcher use oraclejdk7
  - mvn surefire:test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
